cache: cargo
dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabihf
env: TARGET=x86_64-unknown-linux-gnu

install:
  # NOTE(TRAVIS_BRANCH) Travis is configured to only build *pushes* (not PRs).
  - if [ $TRAVIS_BRANCH != master ] || [ $TRAVIS_EVENT_TYPE = cron ]; then
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y;
      source ~/.cargo/env;
      rustup component add rust-src;
    fi

script:
  # NOTE(TRAVIS_BRANCH) See the NOTE in the `install` section
  # if: check if `src/examples` has not been re-generated
  # chmod: Travis can't cache files that are not readable by "others"
  - if [ $TRAVIS_BRANCH != master ] || [ $TRAVIS_EVENT_TYPE = cron ]; then
      cargo generate-lockfile;
      sh ci/run-docker.sh $TARGET;
      if [ $TARGET = x86_64-unknown-linux-gnu ]; then
        ./gen-examples.sh;
        stdout=$(git status --porcelain);
        test "$stdout" = "" || ( echo "Outdated examples:" && echo "$stdout" && false );
      fi;
      chmod -R a+r $HOME/.cargo;
    fi

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
