[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
description = "A crate to play with the STM32F3DISCOVERY"
documentation = "https://docs.rs/f3"
keywords = ["arm", "cortex-m", "stm32f3discovery", "stm32"]
license = "MIT OR Apache-2.0"
name = "f3"
repository = "https://github.com/japaric/f3"
version = "0.1.0"

[dependencies]
compiler-builtins-snapshot = "0.0.20161008"
cortex-m = "0.1.3"
r0 = "0.1.0"
volatile-register = "0.1.1"

[features]
default = ["compiler-builtins-snapshot/memcpy"]

[profile.release]
lto = true
